"""Pydantic domain models and LangGraph state schemas."""
import operator
from typing import Annotated

from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field


class Researcher(BaseModel):
    """A researcher persona generated by the LLM."""
    name: str = Field(description="Full name of the researcher persona.")
    role: str = Field(description="Professional role, e.g. 'Battery materials scientist'.")
    focus: str = Field(description="One sentence: the specific angle this researcher investigates.")

    @property
    def persona(self) -> str:
        return f"Name: {self.name}\nRole: {self.role}\nFocus: {self.focus}"


class ResearcherTeam(BaseModel):
    """Structured output for researcher-team generation."""
    researchers: list[Researcher] = Field(description="The team of researcher personas.")


class SearchQuery(BaseModel):
    """Structured output for search-query generation."""
    query: str = Field(description="A well-formed web search query.")


class CompletedResearch(BaseModel):
    """One researcher's finished, persona-attributed research memo."""
    researcher: Researcher
    summary: str
    sources: list[str]


class ResearchState(BaseModel):
    """Parent graph state."""
    topic: str
    num_researchers: int = 3
    max_turns: int = 2
    researchers: list[Researcher] = []
    human_feedback: str | None = None
    completed_research: Annotated[list[CompletedResearch], operator.add] = []
    intro: str = ""
    body: str = ""
    conclusion: str = ""
    final_report: str = ""


class InterviewState(BaseModel):
    """Research subgraph state (one instance per researcher, run in parallel)."""
    messages: Annotated[list, add_messages] = []
    researcher: Researcher
    topic: str = ""
    max_turns: int = 2
    turn_count: int = 0
    context: Annotated[list[str], operator.add] = []
    sources: Annotated[list[str], operator.add] = []
    # Shares its name with ResearchState so subgraph results merge into the parent.
    completed_research: Annotated[list[CompletedResearch], operator.add] = []
